### ISSUE TITLE
Support multiple-cursors

### ISSUE THREAD

**Issue by PythonNut** [leoliu/easy-kill#23]
When easy-killing with [`multiple-cursors.el`](https://github.com/magnars/multiple-cursors.el), the same text is put in every cursors kill ring, when it should be different for each one as the regions permit.

**Comment by leoliu** [comment]
Hi @PythonNut,

thanks for the report. I am not a user of `multiple-cursors.el` so i have no idea what problem this is. Maybe provide me with detailed steps to reproduce the problem I might be able to propose a fix. Otherwise I'd have to rely on someone else's expertise for a fix.

cheers,
Leo

**Comment by knu** [comment]
Since `easy-kill-candidate` is a global variable, multiple-cursors can't handle easy-kill selection on the per-cursor basis.  You'll have to replace it with some function call like `(easy-kill-candidate-overlay)` which in turn is implemented so it returns the candidate overlay based on the current cursor position.

**Comment by PythonNut** [comment]
Actually, it seems to have come down to a rather obscure setting in my config.

@knu despite the fact that easy-kill-candidate is global, I don't think it effects `multiple-cursors` since the calls to `easy-kill` are done one-at-a-time, not in parallel. 

For anyone else who sees this strange issue, try this:

```emacs
(setq x-select-enable-primary nil)
```

And see if that helps.

**Comment by knu** [comment]
One at a time, with all cursors sharing the easy-kill selection state and sharing one kill ring.

**Comment by PythonNut** [comment]
It works for me, so I'm happy.
