### ISSUE TITLE
use ace-jump for string-to-character?

### ISSUE THREAD

**Issue by jack99999** [leoliu/easy-kill#24]
hi

i often use ace-jump-mode to move around... and ace-jump-zap for killing text...

i find ace-jump to be more flexible than the string-up-to-character mechanism in easy kill. but, of course, the ace-jump works only for visible text.

is it possible to include ace-jump style movement for easy kill? i would prefer also to keep the existing style.

cheers
jack

**Comment by knu** [comment]
`easy-kill` and `ace-jump-*-mode` are both modal commands, so there's no clean way to combine them.
However, I've done a bit of a hack and just pushed it to [kill-easy-extras.el](https://github.com/knu/easy-kill-extras.el) which you can try.

**Comment by jack99999** [comment]
that's absolutely brilliant! it works beautifully.

of course, there is a minor bug... when going to a character earlier in the buffer:
      ace-jump-char-mode works 
      ace-jump-word-mode fails unless the character is on the same line as the cursor.

for my own purposes that's a trivial restriction... i tend to copy forwards anyway.. but if you are striving for perfection...

many thanks

jack

**Comment by knu** [comment]
Good for you.  I need some more information about the problem with `ace-jump-word-mode` as it doesn't reproduce for me.

**Comment by jack99999** [comment]
i did pick up a slightly later change that you made... the jump backwards is mostly working, dunno whether that was you fixing something or me not getting it clear.

anyway, moving on... it fails backwards and forwards if there is just one candidate.  i have ace-jump set to jump immediately if there is a single candidate.

**Comment by knu** [comment]
It's a hack after all since ace-jump has no working hooks that are required to implement this functionality, but I think I have the problems with direct jump fixed.  If you still have a problem, please file an issue [here](https://github.com/knu/easy-kill-extras.el/issues), thanks.

**Comment by jack99999** [comment]
just updated... seems to be working perfectly!

many thanks, that's absolutely superb. 

jack

**Comment by knu** [comment]
Glad it worked!
