### ISSUE TITLE
wrong number of arguments <=, 3

### ISSUE THREAD

**Issue by yuandaxing** [leoliu/easy-kill#25]
Hi,
  I'm a new emacs user. my emacs version is  "GNU Emacs 24.3.1"
below is my easy-kill configuration 
(global-set-key [remap kill-ring-save] 'easy-kill)
(global-set-key [remap mark-sexp] 'easy-mark)

below is the description of M-w 

M-w runs the command easy-kill, which is an interactive autoloaded
compiled Lisp function in `easy-kill.el'.
......

when i type M-w, it give me the error 
wrong number of arguments <=, 3

**Comment by leoliu** [comment]
Sorry for this bug.

**Comment by yuandaxing** [comment]
thank you very much, work fine now.
