### ISSUE TITLE
pressing easy-kill-unhighlight-key displays message "thing copied", but not actually copied.

### ISSUE THREAD

**Issue by YangZhao11** [leoliu/easy-kill#26]
how to reproduce:
(setq easy-kill-unhighlight-key " ")

then press `M-w SPC`. There is a message in minibuffer that says "line copied", but if you check the kill ring (`C-h v kill-ring`), the line is not actually copied.

**Comment by leoliu** [comment]
Hi @YangZhao11,

Many thanks for the report.

Leo
