### ISSUE TITLE
Cycle through easy-mark-try-things

### ISSUE THREAD

**Issue by indigoviolet** [leoliu/easy-kill#29]
Is there a way to cycle through the various mark targets? I'd imagine something like, we'd go in order `easy-mark-try-things`, upon hitting `C-SPC` repeatedly.

**Comment by leoliu** [comment]
Not at the moment. This was not favoured at the time because each individual thing can be addressed with a single key press.

**Comment by indigoviolet** [comment]
ok. please consider this a feature request- pressing the same key can IMO
be quicker sometimes because it avoids the cognitive overhead of "looking
up" the right key; and it is also easier to recover from a mistake.

**Comment by leoliu** [comment]
ok. will see what can be done. Thanks for the request.

**Comment by leoliu** [comment]
@indigoviolet,

Thanks for your patience. I intend to add something along these lines after some more testing. Could you try it and see if this is something that you have in mind? Thanks.

```
diff --git a/easy-kill.el b/easy-kill.el
index 07d63ea7..870c1a9a 100644
--- a/easy-kill.el
+++ b/easy-kill.el
@@ -1,6 +1,6 @@
 ;;; easy-kill.el --- kill & mark things easily       -*- lexical-binding: t; -*-
 
-;; Copyright (C) 2013-2015  Free Software Foundation, Inc.
+;; Copyright (C) 2013-2018  Free Software Foundation, Inc.
 
 ;; Author: Leo Liu <sdl.web@gmail.com>
 ;; Version: 0.9.4
@@ -119,6 +119,7 @@ (defvar easy-kill-base-map
     (define-key map "-" 'easy-kill-shrink)
     (define-key map "+" 'easy-kill-expand)
     (define-key map "=" 'easy-kill-expand)
+    (define-key map " " 'easy-kill-cycle)
     (define-key map "@" 'easy-kill-append)
     ;; Note: didn't pick C-h because it is a very useful prefix key.
     (define-key map "?" 'easy-kill-help)
@@ -380,6 +381,22 @@ (defun easy-kill-expand ()
   (interactive)
   (easy-kill-thing nil '+))
 
+(defun easy-kill-cycle (&optional thing)
+  (interactive)
+  (let* ((thing (or thing (easy-kill-get thing)))
+         (next (easy-kill-cycle-next thing)))
+    (easy-kill-thing next)
+    (if (eq next (easy-kill-get thing))
+        (easy-kill-echo "%s" next)
+      (easy-kill-cycle next))))
+
+(defun easy-kill-cycle-next (thing)
+  (cl-flet ((thing-name (thing)
+              (if (symbolp (cdr thing)) (cdr thing) (cl-second thing))))
+    (thing-name (cl-loop for (head . tail) on easy-kill-alist
+                         when (eq thing (thing-name head))
+                         return (car (or tail easy-kill-alist))))))
+
 (defun easy-kill-digit-argument (n)
   "Expand selection by N number of things.
 If N is 0 shrink the selection to the initial size before any
```

**Comment by indigoviolet** [comment]
@leoliu, Thank you for adding this feature.

I tried it and it works really nicely. 

fyi- I think there might be a minor edge case with some mark targets from `easy-kill-extras` like `string-up-to-char-backward` where if a target cannot be found, it interrupts the cycling, but this doesn't bother me much.

**Comment by leoliu** [comment]
@indigoviolet Glad to hear it.

@knu Do you have time to take a look at the new command `easy-kill-cycle` and its interaction with `string-up-to-char-backward`? Thanks.

**Comment by knu** [comment]
Targets like `string-up-to-char-forward` and `string-up-to-char-backward` prompt you for a key press, so they may not really fit in cycling, I guess.

I recently added integration with `expand-region` to easy-kill-extras, which may suit your needs.

**Comment by leoliu** [comment]
@indigoviolet and @knu, Just introduced `easy-kill-cycle-ignored` for convenience.
