### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by c02y** [leoliu/easy-kill#32]
It seems several functions of `easy-kill` do not work with language like C/C++

1. M-w l: save list at point (enclosing sexp)
2. M-w d: save defun at point
3. M-w D: save current defun name

If they work with C/C++, that would be better.

And when I `M-w` at the pointer, it is better to show some hints that `l`, `d` and other keys can do more things, like `which-key`, since `M-w` is more like a prefix.

**Comment by knu** [comment]
They all work for me in c-mode and c++-mode.  Can you show any failing example for reproduction?

**Comment by knu** [comment]
Also, "Suggestions" is not a good name for an issue.  Please describe what you are trying to report, and file an issue for one thing at a time.

**Comment by leoliu** [comment]
Hi @c02y, If C/C++ files are in the correct major mode (e.g. `c-mode` or `c++-mode`) these key bindings should work. Let us know if not.

**Comment by c02y** [comment]
My bad, I created an org file containing pure C code in it (not in org code block).

Yes, it works, but in your README.rst file, you didn't mention `list-wise` works for C/C++.

 I'll post another issue about the hits at the mode line.
