### ISSUE TITLE
Show hits of keys in the minibuffer like which-key

### ISSUE THREAD

**Issue by c02y** [leoliu/easy-kill#34]
When I use `M-w` key is like a prefix key to do easy-kill, how to display available keys for their actions like which-key, since I cannot remember what the full list of shortcuts `easy-kill` provides. I don't know if you can take advantage of `which-key` or not.

![which-key-minibuffer](https://user-images.githubusercontent.com/2135996/48324699-f8cf6d00-e66c-11e8-91c1-9eb1e5ad8feb.png)

**Comment by leoliu** [comment]
`M-w` is both a normal key and a prefix key. `M-w ?` might be of some help.

**Comment by c02y** [comment]
BTW, how can get the help page when I use easy-mark (C-M-@)?

**Comment by leoliu** [comment]
Does `C-M-@ ?` work?

**Comment by c02y** [comment]
Yes, thanks, I thought it is `M-w ?` too.
