### ISSUE TITLE
Get error when calling easy-kill-delete-region

### ISSUE THREAD

**Issue by JSpenced** [leoliu/easy-kill#38]
I get an error when calling this function. `easy-kill-delete-region`.

The error is:

`funcall-interactively: Wrong type argument: integer-or-marker-p, nil`

**Comment by leoliu** [comment]
I cannot reproduce it here.

**Comment by JSpenced** [comment]
Okay, is there a way to get more info in regards to the error?

**Comment by JSpenced** [comment]
Nevermind, I realized that only works if you've already called easy-kill base call. It is working fine. Thanks
