### ISSUE TITLE
Get a remapped C-w to work just during easy-kill invocation or map another key to perform kill-region.

### ISSUE THREAD

**Issue by JSpenced** [leoliu/easy-kill#39]
Currently, I use easy-kill but I have mapped kill-region to `s-x` which I normally don't use.
The mapping for `C-w` is `whole-line-or-region-kill-region` which kills the whole line if there is no active-region or it kills the region. I guess I have two questions:

Is there a way to get `C-w` to work as desired when easy-kill is invoked using `M-w` so the `C-w` gets switched back to kill-region so it works properly. Or probably even better can I just bind another key like `k` or `,` to `kill-region`?

**Comment by leoliu** [comment]
easy-kill doesn't activate the region so calling vanilla kill-region won't work in that context. but you can bind keys in easy-kill-mode, I think, by putting them in `easy-kill-base-map`.

**Comment by JSpenced** [comment]
Okay, yeah that works.
