### ISSUE TITLE
Respect `delete-selection-mode`

### ISSUE THREAD

**Issue by butter-radish** [leoliu/easy-kill#44]
If `delete-selection-mode` is active then can `easy-kill`'s regions/selections respect it, and delete the text I've selected when I begin typing?

**Comment by leoliu** [comment]
@butter-radish 

Sorry for the delay. `easy-kill` doesn't activate the region so `delete-selection-mode` doesn't know what to delete. But `C-w` can be used to delete the selection by `easy-kill`.

Note also there is `easy-mark` which should work nicely with it.

Hope this helps ;)
