### ISSUE TITLE
M-w w doesn't select sigil

### ISSUE THREAD

**Issue by yPhil-gh** [leoliu/easy-kill#45]
Hi ; this package is fantastic. As it is, it already boosted my production +10% and counting. Thank you **very much**.

Now, I'd like to know how to either:

- Redefine the "word" `thing` to include a possible `$` sigil, or (probably preferably, I don't know right now)
- Define my own `thing` so that pressing `M-w v` would select my variable, ie the word with the possible `$` sigil?

**Comment by leoliu** [comment]
Thanks ;)

Things are defined by `thingatpt` in stock emacs.

If `$` doesn't have word syntax then it can't be selected using `word` but in most cases you can use `sexp` instead. If you really like to define a new thing just follow examples in `thingatpt` for example `(define-thing-chars filename thing-at-point-file-name-chars)` may get you started.

You can then add the new thing to `easy-kill-alist`.
