### ISSUE TITLE
this package looks like not working on emacs 29.4 and 30.1

### ISSUE THREAD

**Issue by ynnebhc** [leoliu/easy-kill#47]
e.g. copy word not working any more in these latest emacs version. could you please update accordingly? many thanks.

**Comment by leoliu** [comment]
I am using it daily on Emacs 29.4 so it should work.  Can you show what is not working? Thanks.

**Comment by ynnebhc** [comment]
I just upgraded to emacs 30.1 and copy word by alt-w w always copy the same
as alt-w s.

Sorry for the confusion.

**Comment by ynnebhc** [comment]
I retested on emacs30 and it still works but seems have different results,
esp. with var with underscore. Please close this ticket. Thanks

**Comment by leoliu** [comment]
@ynnebhc a lot of things that this lib does is done through `thingatpt`.  For example if word with underscore is copied wrong likely underscore does not have word syntax. Hope this helps.
